# Generated by Django 5.1.2 on 2025-02-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(help_text='Выберите поставщика', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='network.supplier', verbose_name='поставщик'),
        ),
    ]
