# Generated by Django 5.1.2 on 2025-02-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'звено сети', 'verbose_name_plural': 'звенья сети'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Выберите поставщика', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='network.supplier', verbose_name='поставщик'),
        ),
    ]
